compliance/compliance/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dataapp.urls', namespace='dataapp')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

compliance/dataapp/urls.py
from django.urls import path
from . import views

app_name = 'dataapp'

urlpatterns=[
    path('', views.index, name="index"),
    path('register/', views.register, name="register"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('post_list/', views.post_list, name="post_list"),
    path('post_list/<int:pk>/', views.post_delete, name='post_delete'),
    path('post_list/<slug:post>/', views.post_detail, name='post_detail'),
    path('post_list/<slug:post>/handle_high_level/', views.handle_high_level, name='handle_high_level'),
    path('post_list/<slug:post>/generate_report/',views.generate_report,name='generate_report'),
    path('new_post/', views.MainView.as_view(), name="upload-view"),
    path('new_post/upload/', views.file_upload_view, name="upload_view"),
    path('testtext/dlp/',views.dlptext,name='dlp'),
    ]

compliance/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>数据合规{% block title %}{% endblock title %}</title>

    <!-- Bootstrap CSS-->
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet"  crossorigin="anonymous">

    <!-- static file -->
    <link href="{% static "/css/style.css" %}" rel="stylesheet">
     <!-- highlight js -->
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/monokai-sublime.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js"></script>
    <script>hljs.initHighlightingOnLoad();</script>

    <!-- 导航栏-->
    <link rel="icon" type="image/x-icon" href="{% static "/img/favicon.ico" %}" />
        <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static "/css/freestyles.css" %}" rel="stylesheet" >


    <!--注册登录-->
    <!-- Font Icon -->
    <link rel="stylesheet" href="/static/fonts/material-icon/css/material-design-iconic-font.min.css">
    <!-- Main css -->
    <link rel="stylesheet" href="{% static "/css/loginstyle.css" %}" >

</head>


<body>

  <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light" id="mainNav"  >
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="/">Data Compliance</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/">主页</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">关于</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="/login/">登录</a></li>
                        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="#">退出</a></li>
                    </ul>
                </div>
            </div>
        </nav>


<!--   Page Header-->
        <div class="my-page-header">
            <header class="masthead" >

            </header>

        </div>

        <main >
                    {% block content %}

                    {% endblock content %}
        </main>






    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="/static/bootstrap/js/bootstrap.bundle.min.js"  crossorigin="anonymous"></script>

    <script src="/static/js/scripts.js"></script>

    <!--注册登录-->
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/main.js"></script>

</body>
</html>

compliance/templates/baseadmin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>数据合规{% block title %}{% endblock title %}</title>
    <link rel="icon" type="image/x-icon" href="{% static "/img/favicon.ico" %}" />

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
    <link href="{% static "/plugins/fontawesome-free/css/all.min.css" %}" rel="stylesheet">
<!--  <link rel="stylesheet" href="/static/plugins/fontawesome-free/css/all.min.css">-->
  <!-- Theme style -->
    <link href="{% static "/dist/css/adminlte.min.css" %}" rel="stylesheet">
<!--  <link rel="stylesheet" href="/static/dist/css/adminlte.min.css">-->
    <!-- 新建图标样式 -->
<!--    <link rel="stylesheet" href="{% static "/dist/css/iconfont.css" %}">-->
     <!-- 上传文件样式 -->
    <link rel="stylesheet" href="{% static "/plugins/dropzone/min/dropzone.min.css" %}">
<!--  自定义样式-->
    <link rel="stylesheet" href="{% static "/css/baseadminstyle.css" %}">
</head>


<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>

    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="nav-link" data-widget="navbar-search" href="#" role="button">
              <i class="fas fa-search"></i>
            </a>
            <div class="navbar-search-block" style="display: none;">
              <form class="form-inline">
                <div class="input-group input-group-sm">
                  <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
                  <div class="input-group-append">
                    <button class="btn btn-navbar" type="submit">
                      <i class="fas fa-search"></i>
                    </button>
                    <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                      <i class="fas fa-times"></i>
                    </button>
                  </div>
                </div>
              </form>
            </div>
          </li>
    </ul>

  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="/" class="brand-link">
      <img src="/static/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Data Compliance</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="/static/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">{{ request.session.user_name }}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item">
            <a href="/post_list/" class="nav-link">
              <i class="nav-icon fas fa-columns"></i>
              <p>
                项目列表
              </p>
            </a>
          </li>

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    {% block content %}

    {% endblock content %}
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->



  <!-- Control Sidebar -->

  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="/static/plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="/static/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!--  App -->
<script src="/static/dist/js/adminlte.min.js"></script>

<!-- 上传文件js -->
<script src="/static/plugins/dropzone/min/dropzone.min.js"></script>

<!-- 自定义样式 -->
<!-- <script src="/static/js/baseadminstyle.js"></script> -->


<script>
      // 高风险数据高亮显示
    $(function(){
      // let mybtn = document.getElementById("high-level");
      window.addEventListener('load', function(){
          var data = JSON.parse("{{data|escapejs}}");
          var tab=document.getElementById("mytable");
          var rows=tab.rows;
          for(var x in data)
          {
            for(var y in data[x])
            {
              rows[parseInt(x)].cells[parseInt(data[x][y])].classList.add('high-level-light');
            }
          }   
      }); 

    });

    // 中风险数据高亮显示
    $(function(){
      // let midmybtn = document.getElementById("middle-level");
      window.addEventListener('load', function(){
          var data = JSON.parse("{{middle_data|escapejs}}");
          var tab=document.getElementById("mytable");
          var rows=tab.rows;
          
          for(var x in data)
          {
            for(var y in data[x])
            {
              rows[parseInt(x)].cells[parseInt(data[x][y])].classList.add('middle-level-light');
            } 
          }   
      }); 

    });


    // 处理高风险数据
    $(function(){
      let mybtn = document.getElementById("handel-high-level");
      mybtn.addEventListener('click', function(){
        var time = new Date();
        var handle_time = time.toLocaleString( );                      //获取要传到后台d的点击事件发生的时间
        $.ajax({
            type: "GET",
            url: "{{post.get_absolute_url}}?high_level_handle_time="+handle_time,   //后台处理函数的url
            // data:handle_time,
            success: function replaceDoc()                                //成功后执行此函数
              {
                  window.location.replace("{{post.get_absolute_url}}?high_level_handle_time="+handle_time)    
              },           
        });

          // var data = JSON.parse("{{data|escapejs}}");
          // var tab=document.getElementById("mytable");
          // var rows=tab.rows;
          // for(var x in data)
          // {
          //   for(var y in data[x])
          //   {
          //     rows[parseInt(x)].cells[parseInt(data[x][y])].classList.add('high-level-light');
          //   }
          // }   
      }); 

    });

     
    Dropzone.autoDiscover = false;
    new Dropzone("#upload",{
          clickable: ".dropzone",
          url: "upload/",
          maxFiles:2,
          maxFilesize:50,
          acceptedFiles:'.excel, .png, .csv',
          previewsContainer: "#previewsContainer",
          uploadMultiple: true,
          autoProcessQueue: false,
          init() {
            var myDropzone = this;
            this.element.querySelector("[type=submit]").addEventListener("click", function(e){
              e.preventDefault();
              e.stopPropagation();
              myDropzone.processQueue();
            });
            this.on("queuecomplete", function() {
            //Redirect URL
             'post_list/';
            });
          }
        });


        // $(function() { 
        //     //Dropzone class
        //     var myDropzone = new Dropzone(".dropzone");
        //     myDropzone.on("queuecomplete", function() {
        //         //Redirect URL
        //          'http://localhost:8000/post_list/';
        //     }); 
        // });


        // 文件上传区域点击或者拖拽后，不显示里面的文字
        let btn = document.getElementById("previewsContainer");
        btn.addEventListener('drop', function(){
            var t = document.getElementById('my-btn')
            t.style.display = 'none';
        });
        btn.addEventListener('click', function(){
            var t = document.getElementById('my-btn')
            t.style.display = 'none';
        });


</script>



</body>
</html>

compliance/templates/generate_report.html
{% extends 'baseadmin.html' %}

{% block title %} - 生成报告{% endblock title %}

{% block content %}



 <section class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1>项目报告</h1>
        </div>
          <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item">
                <a  href="{{post.get_absolute_url}}">
                <button type="button" class="btn btn-block btn-outline-secondary btn-lg">返回</button>
                </a>
            </li>
          </ol>
        </div>
      </div>
    </div>
  </section>

  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-12">
          <div class="callout callout-info">
            <h5><i class="fas fa-info"></i> 温馨提示:</h5>
            此页面为您的数据合规报告，包含您原始数据的合规得分，以及您的详细合规操作，点击pdf按钮即可生成您的合规分析报告。
          </div>


          <!-- Main content -->
          <div class="invoice p-3 mb-3">
            <!-- title row -->
            <div class="row">
              <div class="col-12">
                <h4>
                  <i class="fas fa-globe"></i> Data Compliance.
                  <small class="float-right">Date: 2/10/2014</small>
                </h4>
              </div>
              <!-- /.col -->
            </div>
            <!-- info row -->
            <div class="row invoice-info">
              <div class="col-sm-4 invoice-col">
                From
                <address>
                  <strong>Admin, Inc.</strong><br>
                  795 Folsom Ave, Suite 600<br>
                  San Francisco, CA 94107<br>
                  Phone: (804) 123-5432<br>
                  Email: info@almasaeedstudio.com
                </address>
              </div>
              <!-- /.col -->
              <div class="col-sm-4 invoice-col">
                To
                <address>
                  <strong>John Doe</strong><br>
                  795 Folsom Ave, Suite 600<br>
                  San Francisco, CA 94107<br>
                  Phone: (555) 539-1037<br>
                  Email: john.doe@example.com
                </address>
              </div>
              <!-- /.col -->
              <!-- <div class="col-sm-4 invoice-col">
                <b>Invoice #007612</b><br>
                <br>
                <b>Order ID:</b> 4F3S8J<br>
                <b>Payment Due:</b> 2/22/2014<br>
                <b>Account:</b> 968-34567
              </div> -->
              <!-- /.col -->
            </div>
            <!-- /.row -->

            <!-- Table row -->
            <div class="row">
              <div class="col-12 table-responsive">
                <table class="table table-striped">
                  <thead>
                  <tr>
                    <th>序号</th>
                    <th>处理时间</th>
                    <th>处理数据量</th>
                    <th>处理内容描述</th>
                    <!-- <th>Subtotal</th> -->
                  </tr>
                  </thead>
                  <tbody>
                  <tr>
                    <td>1</td>
                    <td>Call of Duty</td>
                    <td>455-981-221</td>
                    <td>El snort testosterone trophy driving gloves handsome</td>
                    <!-- <td>$64.50</td> -->
                  </tr>
                  <tr>
                    <td>1</td>
                    <td>Need for Speed IV</td>
                    <td>247-925-726</td>
                    <td>Wes Anderson umami biodiesel</td>
                    <!-- <td>$50.00</td> -->
                  </tr>
                  <tr>
                    <td>1</td>
                    <td>Monsters DVD</td>
                    <td>735-845-642</td>
                    <td>Terry Richardson helvetica tousled street art master</td>
                    <!-- <td>$10.70</td> -->
                  </tr>
                  <tr>
                    <td>1</td>
                    <td>Grown Ups Blue Ray</td>
                    <td>422-568-642</td>
                    <td>Tousled lomo letterpress</td>
                    <!-- <td>$25.99</td> -->
                  </tr>
                  </tbody>
                </table>
              </div>
              <!-- /.col -->
            </div>
            <!-- /.row -->

            <div class="row">
              <!-- accepted payments column -->
              <div class="col-6">
                <p class="lead">Payment Methods:</p>
                <img src="../../dist/img/credit/visa.png" alt="Visa">
                <img src="../../dist/img/credit/mastercard.png" alt="Mastercard">
                <img src="../../dist/img/credit/american-express.png" alt="American Express">
                <img src="../../dist/img/credit/paypal2.png" alt="Paypal">

                <p class="text-muted well well-sm shadow-none" style="margin-top: 10px;">
                  Etsy doostang zoodles disqus groupon greplin oooj voxy zoodles, weebly ning heekya handango imeem
                  plugg
                  dopplr jibjab, movity jajah plickers sifteo edmodo ifttt zimbra.
                </p>
              </div>
              <!-- /.col -->
              <div class="col-6">
                <p class="lead">合规得分</p>

                <div class="table-responsive">
                  <table class="table">
                    <tbody><tr>
                      <th style="width:50%">合规性:</th>
                      <td>55%</td>
                    </tr>
                    <tr>
                      <th>隐私性：</th>
                      <td>70%</td>
                    </tr>
                    <tr>
                      <th>完整性:</th>
                      <td>30%</td>
                    </tr>
                    <tr>
                      <th>规范性:</th>
                      <td>90%</td>
                    </tr>
                  </tbody></table>
                </div>
              </div>
              <!-- /.col -->
            </div>
            <!-- /.row -->

            <!-- this row will not appear when printing -->
            <div class="row no-print">
              <div class="col-12">
                <!-- <a href="invoice-print.html" rel="noopener" target="_blank" class="btn btn-default"><i class="fas fa-print"></i> Print</a>
                <button type="button" class="btn btn-success float-right"><i class="far fa-credit-card"></i> Submit
                  Payment
                </button> -->
                <button type="button" class="btn btn-primary float-right" style="margin-right: 5px;">
                  <i class="fas fa-download"></i> 生成PDF
                </button>
              </div>
            </div>
          </div>
          <!-- /.invoice -->
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </section>


  {% endblock content %}  

compliance/templates/landing.html
{% load static %}
<!DOCTYPE html>
<body>
	<div style="width: 40%;
	border: 1px solid black;
	background-color: lightcyan;
	font-family: Helvetica, sans-serif;">
		<div style="margin: 5%;">
			<h1>
				<u>Dictionary Data</u>
			</h1>
			<h2>
				<u>All Data</u>
			</h2>
			<h4 id='alldata'></h4><br>
			<h2>
				<u>Neat Data</u>
			</h2>
			<h4 id='neatdata'></h4>
		</div>
	</div>
</body>
</html>
<script>
	var data = JSON.parse("{{data|escapejs}}");
	var dataNode = document.getElementById('alldata');
    alert('111111');
	dataNode.innerHTML+="{{data|escapejs}}";
	dataNode = document.getElementById('neatdata');
	for(var x in data){
		dataNode.innerHTML+=x+' : '+data[x]+'<br><br>';
	}
</script>

compliance/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>数据合规{% block title %}{% endblock title %}</title>
    <link rel="icon" type="image/x-icon" href="{% static "/img/favicon.ico" %}" />

    <link rel="stylesheet" href="fonts/material-icon/css/material-design-iconic-font.min.css">
    <!-- Main css -->
    <link rel="stylesheet" href="{% static "/css/loginstyle.css" %}" />
</head>
<body>

    <div class="main">

        <section class="signup">
            <!-- <img src="files/signup-bg.jpg" alt=""> -->
            <div class="container">
                <div class="signup-content">
                    <form method="POST" id="signup-form" class="signup-form">
                        {% csrf_token %}
                        <h2 class="form-title">Create account</h2>
                        <div class="form-group">
                            <input type="text" class="form-input" name="username" id="name" placeholder="Your Name"/>
                        </div>

                        <div class="form-group">
                            <input type="password" class="form-input" name="password" id="password" placeholder="Password"/>
                            <span toggle="#password" class="zmdi zmdi-eye field-icon toggle-password"></span>
                        </div>

                        <div class="form-group">

                            <label  class="label-agree-term"><span><span></span></span>
                                {% if message %}
                                  <div class="alert alert-warning">{{ message }}</div>
                                {% endif %}
                            </label>
                        </div>
                        <div class="form-group">
                            <input type="submit" name="submit" id="submit" class="form-submit" value="Sign up"/>
                        </div>
                    </form>
                    <p class="loginhere">
                        Don't have an account ? <a href="/register/" class="loginhere-link">Register here</a>
                    </p>
                </div>
            </div>
        </section>

    </div>

    <!-- JS -->
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/main.js"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

compliance/templates/login2.html
<div class="card card-primary card-outline">
    <div class="card-header">
        <h3 class="card-title">
            <i class="far fa-chart-bar"></i>
            Donut Chart
        </h3>

        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse">
            <i class="fas fa-minus"></i>
            </button>
            <button type="button" class="btn btn-tool" data-card-widget="remove">
            <i class="fas fa-times"></i>
            </button>
        </div>
    </div>
    <div class="card-body">
        <div id="donut-chart" style="height: 300px; padding: 0px; position: relative;">
            <canvas class="flot-base" width="740" height="600" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 370px; height: 300px;">
            </canvas>
            <canvas class="flot-overlay" width="740" height="600" style="direction: ltr; position: absolute; left: 0px; top: 0px; width: 370px; height: 300px;">
            </canvas>
            <span class="pieLabel" id="pieLabel0" style="position: absolute; top: 69.5px; left: 242.957px;">
                <div style="font-size:13px; text-align:center; padding:2px; color: #fff; font-weight: 600;">
                    Series2<br>30%
                </div>
            </span>
            <span class="pieLabel" id="pieLabel1" style="position: absolute; top: 209.5px; left: 220.957px;">
                <div style="font-size:13px; text-align:center; padding:2px; color: #fff; font-weight: 600;">
                    Series3<br>20%
                </div>
            </span>
            <span class="pieLabel" id="pieLabel2" style="position: absolute; top: 128.5px; left: 61.957px;">
                <div style="font-size:13px; text-align:center; padding:2px; color: #fff; font-weight: 600;">
                    Series4<br>50%
                </div>
            </span>
        </div>
    </div>
    <!-- /.card-body-->
</div>

compliance/templates/new_post.html
{% extends 'baseadmin.html' %}

{% block title %} - {{post.title}}{% endblock title %}

{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>新建项目</h1>
          </div>
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item">
                  <a  href="/post_list/">
                  <button type="button" class="btn btn-block btn-outline-secondary btn-lg">返回</button>
                  </a>
              </li>
            </ol>
          </div>
        </div>
      </div>
    </section>


    <section class="content mycontent">


          <div class="card card-secondary mycard">
            <div class="card-header">
              <h3 class="card-title">项目信息</h3>

              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
                  <i class="fas fa-minus"></i>
                </button>
              </div>
            </div>
            <div class="card-body" style="display: block;">



<!--                 上传文件-->

                    {% block content1 %}

                    {% endblock %}

<!-- end             上传文件-->

            </div>
          </div>


    </section>



{% endblock content %}













compliance/templates/post_list.html
{% extends 'baseadmin.html' %}

{% block title %} - 项目列表{% endblock title %}

{% block content %}
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>项目列表</h1>
          </div>
            <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item">
                  <a  href="/new_post/">
                     <button type="button" class="btn btn-block btn-outline-secondary btn-lg">新建</button>
                  </a>
              </li>
            </ol>
          </div>
        </div>
      </div>
        <!-- /.container-fluid -->
    </section>



    <!-- Main content -->
    <section class="content">

      <!-- Default box -->
      <div class="card mycard">
        <div class="card-body p-0">
          <table class="table table-striped projects">
              <thead>
                  <tr>
                      <th style="width: 1%">
                          #
                      </th>
                      <th style="width: 20%">
                          项目名称
                      </th>
                      <th>
                          项目描述
                      </th>
                      <th style="width: 8%" class="text-center">
                          状态
                      </th>
                      <th style="width: 20%">
                      </th>
                  </tr>
              </thead>

              {% for post in posts %}
              <tbody>
                  <tr>
                      <td>
                          #
                      </td>
                      <td>
                          <a>
                              {{ post.title }}
                          </a>
                          <br/>
                          <small>
                              Created {{ post.publish.date }}
                          </small>
                      </td>
                      <td class="project_progress">
                          <a>
                              {{ post.body|safe|striptags|truncatechars:100 }}
                          </a>

                      </td>
                      
                      <td class="project-state">
                          <span class="badge badge-success">{{ post.status }}</span>
                      </td>
                      
                      
                      
                      <td class="project-actions text-right">
                          <a class="btn btn-primary btn-sm" href ="{{post.get_absolute_url}}">
                              <i class="fas fa-folder">
                              </i>
                              View
                          </a>  
                          
                          <a class="btn btn-danger btn-sm" onclick="window.location = '{% url 'dataapp:post_delete' post.id %}' " herf="###">
                            <i class="fas fa-trash">
                            </i>
                            Delete
                          </a>
                      </td> 
                  </tr>

              </tbody>
              {% endfor %}
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->

    </section>


{% endblock content %}